# Generated by Django 2.0.1 on 2018-02-15 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='mambers',
            new_name='members',
        ),
    ]
